/** Full illustration list — placeholder artwork for now. */
window.ILLUSTRATIONS = [
  {
    id: "add-on",
    name: "Add on",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/add-on.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "african-american-figure",
    name: "African-American Figure",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "alligator",
    name: "Alligator",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrow-down",
    name: "Arrow, down",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrow-long-dashed",
    name: "Arrow, long dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrow-short-dashed",
    name: "Arrow, short dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrows-thin-inward",
    name: "Arrows, thin inward",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrows-vertical-dashed",
    name: "Arrows, vertical dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "artist-palette",
    name: "Artist palette",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "athlete",
    name: "Athlete",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avatar-running",
    name: "Avatar Running",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avatar-stumbling",
    name: "Avatar stumbling",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avatar-with-question-mark",
    name: "Avatar with Question Mark",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avatar-with-talk-bubble",
    name: "Avatar with talk bubble",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avatars-in-a-circle",
    name: "Avatars in a circle",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avocado",
    name: "Avocado",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "baking",
    name: "Baking",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ball",
    name: "Ball",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/ball.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "banana",
    name: "Banana",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bang",
    name: "Bang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "basket",
    name: "Basket",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "basketball",
    name: "Basketball",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bat",
    name: "Bat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bathtub",
    name: "Bathtub",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "beaker",
    name: "Beaker",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bear",
    name: "Bear",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bear.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bear-on-chair",
    name: "Bear on Chair",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bear-with-plate-of-food",
    name: "Bear with Plate of Food",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bed",
    name: "Bed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bee",
    name: "Bee",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bee-on-knee",
    name: "Bee on Knee",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "beetle",
    name: "Beetle",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bell",
    name: "Bell",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bib",
    name: "Bib",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bicycle",
    name: "Bicycle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "big",
    name: "Big",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bill",
    name: "Bill",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bird",
    name: "Bird",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bird-cage",
    name: "Bird cage",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bird-with-snacks-popcorn-pizza-pretzel",
    name: "Bird with Snacks (popcorn, pizza, pretzel)",
    tags: ["food", "animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "blob",
    name: "Blob",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "blocks",
    name: "Blocks",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boat",
    name: "Boat",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bobcat",
    name: "Bobcat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bolt",
    name: "Bolt",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bone",
    name: "Bone",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "book",
    name: "Book",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "book-icon-lines",
    name: "Book icon, lines",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "book-icon-stars",
    name: "Book icon, stars",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "books-stack",
    name: "Books, stack",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boombox",
    name: "Boombox",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boot",
    name: "Boot",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boss",
    name: "Boss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bow",
    name: "Bow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "box",
    name: "Box",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "brain-with-gears-think",
    name: "Brain with gears (\"Think\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "brain-gear-with-gauge-think-about-thinking",
    name: "Brain/gear with gauge (\"Think about thinking\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "branching-diagram-elaborate",
    name: "Branching diagram (\"Elaborate\")",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "break",
    name: "Break",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "brush",
    name: "Brush",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bud",
    name: "Bud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "buff",
    name: "Buff",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bunk",
    name: "Bunk",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bus",
    name: "Bus",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "butterfly",
    name: "Butterfly",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "buzz",
    name: "Buzz",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cab",
    name: "Cab",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cactus",
    name: "Cactus",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cactus-with-birds",
    name: "Cactus with birds",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cake",
    name: "Cake",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "can",
    name: "Can",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "car",
    name: "Car",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "carrots",
    name: "Carrots",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cars",
    name: "Cars",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cash",
    name: "Cash",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "castle",
    name: "Castle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat",
    name: "Cat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat-on-lap",
    name: "Cat on lap",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat-on-mat",
    name: "Cat on Mat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat-sleeping",
    name: "Cat sleeping",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat-with-carrots-cake-and-chocolate-chip-cookies",
    name: "Cat with Carrots, Cake, and Chocolate Chip Cookies",
    tags: ["food", "animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cats-two",
    name: "Cats, two",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "caught",
    name: "Caught",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ceiling",
    name: "Ceiling",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chain",
    name: "Chain",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chair",
    name: "Chair",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chat",
    name: "Chat",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chick",
    name: "Chick",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chicken-pen",
    name: "Chicken Pen",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "child",
    name: "Child",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chin",
    name: "Chin",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chocolate-chip-cookies",
    name: "Chocolate Chip Cookies",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chop",
    name: "Chop",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle",
    name: "Circle",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle-of-people-reaching-overhead",
    name: "Circle of people reaching overhead",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle-large-dashed",
    name: "Circle, large dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle-small-dashed",
    name: "Circle, small dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cityscape",
    name: "Cityscape",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "clay",
    name: "Clay",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "clipboard-with-pencil",
    name: "Clipboard with Pencil",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "clothes",
    name: "Clothes",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cloud",
    name: "Cloud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "coach",
    name: "Coach",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "coat",
    name: "Coat",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cod",
    name: "Cod",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "compare-4-similar-shapes",
    name: "Compare (4 similar shapes)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "compassion",
    name: "Compassion",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "contrast-4-different-shapes",
    name: "Contrast (4 different shapes)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cooking",
    name: "Cooking",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cot",
    name: "Cot",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cow",
    name: "Cow",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cube",
    name: "Cube",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cuff",
    name: "Cuff",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cup",
    name: "Cup",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cupcake",
    name: "Cupcake",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cut",
    name: "Cut",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cute",
    name: "Cute",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cylinder",
    name: "Cylinder",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "den",
    name: "Den",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "detective",
    name: "Detective",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dig",
    name: "Dig",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "digging",
    name: "Digging",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dip",
    name: "Dip",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dog",
    name: "Dog",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dog-puppy",
    name: "Dog, puppy",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dog-spotted",
    name: "Dog, spotted",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "doll-falling",
    name: "Doll falling",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "drill",
    name: "Drill",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "drum",
    name: "Drum",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "duck-on-truck",
    name: "Duck on Truck",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "duck-toy",
    name: "Duck Toy",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ear",
    name: "Ear",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "earring",
    name: "Earring",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "egg",
    name: "Egg",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "eight",
    name: "Eight",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "elephant",
    name: "Elephant",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "empathy",
    name: "Empathy",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "eye",
    name: "Eye",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "eyeball",
    name: "Eyeball",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "face-singing",
    name: "Face singing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fang",
    name: "Fang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feeling-vibes",
    name: "Feeling Vibes",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feels-like-hearts",
    name: "Feels like (Hearts)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feet",
    name: "Feet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fern",
    name: "Fern",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feud",
    name: "Feud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "field",
    name: "Field",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figs",
    name: "Figs",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figure-on-chair-looking-at-cactus-sun-clouds-birds",
    name: "Figure on chair looking at cactus, sun, clouds, birds",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figure-balancing-a-box",
    name: "Figure, balancing a box",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figure-hammering-a-nail",
    name: "Figure, hammering a nail",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figure-speaking",
    name: "Figure, speaking",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figure-walking",
    name: "Figure, walking",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "figure-with-directional-arrows",
    name: "Figure, with directional arrows",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fin",
    name: "Fin",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fireplace",
    name: "Fireplace",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fix",
    name: "Fix",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "flamingo",
    name: "Flamingo",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "flower",
    name: "Flower",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "flute",
    name: "Flute",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fly",
    name: "Fly",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fog",
    name: "Fog",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fold",
    name: "Fold",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fox",
    name: "Fox",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fox-on-box",
    name: "Fox on Box",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "frog-on-log",
    name: "Frog on Log",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "frown",
    name: "Frown",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fruit",
    name: "Fruit",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "frying-pan",
    name: "Frying pan",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "full",
    name: "Full",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fuzz",
    name: "Fuzz",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "garbage-truck",
    name: "Garbage truck",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "glasses",
    name: "Glasses",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "glue",
    name: "Glue",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "goat-in-boat",
    name: "Goat in Boat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "gong",
    name: "Gong",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "goose-on-moose",
    name: "Goose on Moose",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "grass",
    name: "Grass",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hand",
    name: "Hand",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hang",
    name: "Hang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hash",
    name: "Hash",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hat-on-bat",
    name: "Hat on Bat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hay",
    name: "Hay",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "head-with-question-mark-in-it",
    name: "Head with Question Mark in it",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "heart",
    name: "Heart",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hearts-dashed",
    name: "Hearts, dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hen",
    name: "Hen",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "high-moon",
    name: "High Moon",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hiss",
    name: "Hiss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hive",
    name: "Hive",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hockey",
    name: "Hockey",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hoe",
    name: "Hoe",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "honk",
    name: "Honk",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hops",
    name: "Hops",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "horse",
    name: "Horse",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "host",
    name: "Host",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "house-with-plant-sun-clouds",
    name: "House with plant, sun, clouds",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "huge",
    name: "Huge",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ice-cube",
    name: "Ice Cube",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ice-flow",
    name: "Ice flow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "idea",
    name: "Idea",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "iguana",
    name: "Iguana",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "integrity",
    name: "Integrity",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "itch",
    name: "Itch",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jazz",
    name: "Jazz",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jelly",
    name: "Jelly",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jellyfish",
    name: "Jellyfish",
    tags: ["food", "animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jet",
    name: "Jet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jug",
    name: "Jug",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "junk",
    name: "Junk",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "key",
    name: "Key",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "kid",
    name: "Kid",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "king",
    name: "King",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "kiss",
    name: "Kiss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "kite",
    name: "Kite",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "knee",
    name: "Knee",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ladder",
    name: "Ladder",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lake",
    name: "Lake",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "launch",
    name: "Launch",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "leaf",
    name: "Leaf",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lemur",
    name: "Lemur",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "less",
    name: "Less",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lid",
    name: "Lid",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "light",
    name: "Light",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "link",
    name: "Link",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lion",
    name: "Lion",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lips",
    name: "Lips",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lipstick",
    name: "Lipstick",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "little",
    name: "Little",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "llama",
    name: "Llama",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "log",
    name: "Log",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "long",
    name: "Long",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "looking-through-binoculars",
    name: "Looking through Binoculars",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "looping-arrows-repeat",
    name: "Looping arrows (\"Repeat\")",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lung",
    name: "Lung",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "magnifying-glass-on-document-give-evidence",
    name: "Magnifying glass on document (\"Give evidence\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mail",
    name: "Mail",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "map",
    name: "Map",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mat",
    name: "Mat",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "medium",
    name: "Medium",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mesh",
    name: "Mesh",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mill",
    name: "Mill",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mincing",
    name: "Mincing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mind",
    name: "Mind",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mink",
    name: "Mink",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "monkey-with-sock-puppets",
    name: "Monkey with sock puppets",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "moons-dashed",
    name: "Moons, dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "moss",
    name: "Moss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "motorcycle",
    name: "Motorcycle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mountain",
    name: "Mountain",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mouse-with-muffins-and-mushrooms",
    name: "Mouse with Muffins and Mushrooms",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mud",
    name: "Mud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "muffins-and-mushrooms",
    name: "Muffins and Mushrooms",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mule",
    name: "Mule",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "music",
    name: "Music",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mute",
    name: "Mute",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "nap",
    name: "Nap",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "newspaper",
    name: "Newspaper",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "newt",
    name: "Newt",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "night",
    name: "Night",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "nine",
    name: "Nine",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "nose",
    name: "Nose",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "octagon",
    name: "Octagon",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "octopus",
    name: "Octopus",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "oval",
    name: "Oval",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "oval-open",
    name: "Oval, Open",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl",
    name: "Owl",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl-with-balloon",
    name: "Owl with Balloon",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl-with-sock",
    name: "Owl with Sock",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl-with-sock-puppets",
    name: "Owl with sock puppets",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paint",
    name: "Paint",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pang",
    name: "Pang",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paper",
    name: "Paper",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paper-with-pencil-think-write-or-sketch",
    name: "Paper with pencil (\"Think, write, or sketch\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "path",
    name: "Path",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paw",
    name: "Paw",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pear",
    name: "Pear",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pencil",
    name: "Pencil",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "penny",
    name: "Penny",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pentagon-dashed",
    name: "Pentagon, dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person",
    name: "Person",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-balancing-shapes-compare",
    name: "Person balancing shapes (\"Compare\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-overboard-boat",
    name: "Person overboard (boat)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-with-audio-player",
    name: "Person with audio player",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pet",
    name: "Pet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "phone",
    name: "Phone",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pie",
    name: "Pie",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "piggy-bank",
    name: "Piggy Bank",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pin",
    name: "Pin",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "plane",
    name: "Plane",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "plate-of-food",
    name: "Plate of Food",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "plates-of-food-and-teacup",
    name: "Plates of Food and Teacup",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "play",
    name: "Play",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "play-dough",
    name: "Play Dough",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "play-with-blocks",
    name: "Play with Blocks",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pop",
    name: "Pop",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pot",
    name: "Pot",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "potato-chips",
    name: "Potato chips",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puff",
    name: "Puff",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pug",
    name: "Pug",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puppets",
    name: "Puppets",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "purse",
    name: "Purse",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puzzle-piece-with-question-mark-challenge",
    name: "Puzzle piece with question mark (\"Challenge\")",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puzzle-pieces",
    name: "Puzzle pieces",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "question-mark",
    name: "Question Mark",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "question-checkmark-speech-bubbles-clarify",
    name: "Question/checkmark speech bubbles (\"Clarify\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "racoon",
    name: "Racoon",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "radio",
    name: "Radio",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rake",
    name: "Rake",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ram",
    name: "Ram",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rat",
    name: "Rat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "reading-a-book",
    name: "Reading a book",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rectangle",
    name: "Rectangle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "respect",
    name: "Respect",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ring",
    name: "Ring",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "road",
    name: "Road",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "road-block",
    name: "Road block",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rod",
    name: "Rod",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "safe",
    name: "Safe",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sand",
    name: "Sand",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sand-castle",
    name: "Sand Castle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sang",
    name: "Sang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sank",
    name: "Sank",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "satellite-dish",
    name: "Satellite dish",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "scale-check-x",
    name: "Scale (check, X)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sell",
    name: "Sell",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shed",
    name: "Shed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sheep",
    name: "Sheep",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shell",
    name: "Shell",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shin",
    name: "Shin",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ship",
    name: "Ship",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shirt",
    name: "Shirt",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shop",
    name: "Shop",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shut",
    name: "Shut",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sing",
    name: "Sing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sink",
    name: "Sink",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sip",
    name: "Sip",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "skunk",
    name: "Skunk",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "small-steps",
    name: "Small steps",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "smile",
    name: "Smile",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "smiley-face-with-open-book",
    name: "Smiley Face with open Book",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snacks-popcorn-pizza-pretzel",
    name: "Snacks (popcorn, pizza, pretzel)",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snail-on-whale",
    name: "Snail on Whale",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snake",
    name: "Snake",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snake-on-cake",
    name: "Snake on Cake",
    tags: ["food", "animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snake-with-soup-strawberries-and-sandwich",
    name: "Snake with Soup, Strawberries, and Sandwich",
    tags: ["food", "animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snow",
    name: "Snow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "soap",
    name: "Soap",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sock",
    name: "Sock",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "soil",
    name: "Soil",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "song",
    name: "Song",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "spades-rocks",
    name: "Spades (Rocks)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "spring",
    name: "Spring",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "square",
    name: "Square",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "squares-dashed",
    name: "Squares, dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "star",
    name: "Star",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "starfish",
    name: "Starfish",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "steam-engine",
    name: "Steam engine",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "stick",
    name: "Stick",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "store",
    name: "Store",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "strawberries",
    name: "Strawberries",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sun-dashed",
    name: "Sun, dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sung",
    name: "Sung",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sunglasses",
    name: "Sunglasses",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sunk",
    name: "Sunk",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "swing",
    name: "Swing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "swings",
    name: "Swings",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tag",
    name: "Tag",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "take-turns-speaking",
    name: "Take turns speaking",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "talk-about-the-question",
    name: "Talk about the question",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tank",
    name: "Tank",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tape-dispenser",
    name: "Tape dispenser",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tea-cup",
    name: "Tea cup",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "teacher-reading-to-students",
    name: "Teacher reading to students",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tears-dashed",
    name: "Tears, dashed",
    tags: ["food", "shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "teeth",
    name: "Teeth",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tern",
    name: "Tern",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "the-magic-bow",
    name: "The Magic Bow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thought",
    name: "Thought",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "three",
    name: "Three",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "three-people",
    name: "Three people",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "throne",
    name: "Throne",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thud",
    name: "Thud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thumb",
    name: "Thumb",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thumbs-up-down-agree-or-disagree",
    name: "Thumbs up/down (\"Agree or disagree\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tiny",
    name: "Tiny",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tire",
    name: "Tire",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tissue",
    name: "Tissue",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toll",
    name: "Toll",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tongs",
    name: "Tongs",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tooth",
    name: "Tooth",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toothbrush",
    name: "Toothbrush",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "top",
    name: "Top",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toss",
    name: "Toss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toy",
    name: "Toy",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tractor",
    name: "Tractor",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "treasure-chest",
    name: "Treasure Chest",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tree",
    name: "Tree",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tree-without-leaves",
    name: "Tree without leaves",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "trees",
    name: "Trees",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "triangle",
    name: "Triangle",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "triangles-dashed",
    name: "Triangles, dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "turtle",
    name: "Turtle",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "turtle-with-plates-of-food-and-teacup",
    name: "Turtle with Plates of Food and Teacup",
    tags: ["food", "animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-business-people-talking",
    name: "Two business people talking",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-figures-happy",
    name: "Two figures (happy)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-people-fishing",
    name: "Two people fishing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-people-talking-explain",
    name: "Two people talking (\"Explain\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "type",
    name: "Type",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "umbrella",
    name: "Umbrella",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "van",
    name: "Van",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "vet",
    name: "Vet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "want-to-play",
    name: "Want to Play",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "warning-symbol",
    name: "Warning Symbol",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "water",
    name: "Water",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "watermelon",
    name: "Watermelon",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "web",
    name: "Web",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wedding-rings",
    name: "Wedding rings",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "where",
    name: "Where",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "whisk",
    name: "Whisk",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wig",
    name: "Wig",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "win",
    name: "Win",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wing",
    name: "Wing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wink",
    name: "Wink",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wolf",
    name: "Wolf",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "woman-with-magnifying-glass",
    name: "Woman with Magnifying Glass",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "yell",
    name: "Yell",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zebra",
    name: "Zebra",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zero",
    name: "Zero",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zig-zag-large-dashed",
    name: "Zig zag, large dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zig-zag-small-dashed",
    name: "Zig zag, small dashed",
    tags: ["shape"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zip",
    name: "Zip",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  }
];
