/** Full illustration list — placeholder artwork for now. */
window.ILLUSTRATIONS = [
  {
    id: "add-on",
    name: "Add on",
    description: "speech, bubble, chat, plus, message",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/add-on.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "alligator",
    name: "Alligator",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "apple",
    name: "Apple",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrow-down",
    name: "Arrow, down",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrow-long-dashed",
    name: "Arrow, long dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrow-short-dashed",
    name: "Arrow, short dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrows-thin-inward",
    name: "Arrows, thin inward",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "arrows-vertical-dashed",
    name: "Arrows, vertical dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "artist-palette",
    name: "Artist palette",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "astronaut",
    name: "Astronaut",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "avocado",
    name: "Avocado",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "baking-whisk",
    name: "Baking/Whisk",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ball",
    name: "Ball",
    description: "sphere, round, play, sport, bounce",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/ball.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "banana",
    name: "Banana",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bang",
    name: "Bang",
    description: "explosion, burst, spark, fireworks, flash",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bang.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "basket",
    name: "Basket",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "basketball",
    name: "Basketball",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bat",
    name: "Bat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bathtub",
    name: "Bathtub",
    description: "bath, wash, bubbles, water, soap",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bathtub.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "beaker",
    name: "Beaker",
    description: "science, lab, chemistry, glass, experiment",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/beaker.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bear",
    name: "Bear",
    description: "animal, brown, scary, mammal, furry",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bear.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bear-on-chair",
    name: "Bear on Chair",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bear-with-plate-of-food",
    name: "Bear with Plate of Food",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bed",
    name: "Bed",
    description: "sleep, rest, furniture, bedroom, night",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bed.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bee",
    name: "Bee",
    description: "insect, yellow, honey, buzz, wings",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bee.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bee-on-knee",
    name: "Bee on Knee",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "beetle",
    name: "Beetle",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bell",
    name: "Bell",
    description: "ring, sound, metal, chime, alert",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bell.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bib",
    name: "Bib",
    description: "baby, feeding, cloth, infant, meal",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bib.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bicycle",
    name: "Bicycle",
    description: "bike, wheels, ride, transport, pedals",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bicycle.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "big",
    name: "Big",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bill",
    name: "Bill",
    description: "money, invoice, payment, dollar, receipt",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bill.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bird",
    name: "Bird",
    description: "animal, wings, fly, feather, avian",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bird.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bird-cage",
    name: "Bird cage",
    description: "cage, pet, metal, enclosure, bird",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bird-cage.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bird-with-snacks-popcorn-pizza-pretzel",
    name: "Bird with Snacks (popcorn, pizza, pretzel)",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "blob",
    name: "Blob",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "blocks",
    name: "Blocks",
    description: "toys, stack, play, build, cubes",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/blocks.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "boat",
    name: "Boat",
    description: "water, sail, travel, ocean, float",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/boat.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bobcat",
    name: "Bobcat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bolt",
    name: "Bolt",
    description: "metal, fastener, tool, hardware, screw",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bolt.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bone",
    name: "Bone",
    description: "skeleton, white, dog, anatomy, fossil",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bone.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "book",
    name: "Book",
    description: "read, pages, learning, story, text",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/book.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "book-icon-lines",
    name: "Book icon, lines",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "book-icon-stars",
    name: "Book icon, stars",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "books-stack",
    name: "Books, stack",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boombox",
    name: "Boombox",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boot",
    name: "Boot",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "boss",
    name: "Boss",
    description: "leader, person, authority, work, manager",
    tags: ["people"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/boss.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bow",
    name: "Bow",
    description: "ribbon, gift, tie, decoration, knot",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bow.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "box",
    name: "Box",
    description: "container, package, storage, cardboard, cube",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/box.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "brain-with-gears-think",
    name: "Brain with gears",
    description: "think, brain, gears, mind, ideas",
    subtitle: "(\"Think\")",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/brain-with-gears.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "brain-gear-with-gauge-think-about-thinking",
    name: "Brain/gear with gauge (\"Think about thinking\")",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "branching-diagram-elaborate",
    name: "Branching diagram (\"Elaborate\")",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "break",
    name: "Break",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "brush",
    name: "Brush",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bud",
    name: "Bud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "buff",
    name: "Buff",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "bunk",
    name: "Bunk",
    description: "bed, sleep, stacked, furniture, share",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bunk.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "bus",
    name: "Bus",
    description: "vehicle, transport, yellow, school, ride",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/bus.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "butterfly",
    name: "Butterfly",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "buzz",
    name: "Buzz",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cab",
    name: "Cab",
    description: "taxi, car, transport, city, ride",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cab.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cactus",
    name: "Cactus",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cactus-with-birds",
    name: "Cactus with birds",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cake",
    name: "Cake",
    description: "dessert, sweet, birthday, frosting, food",
    tags: ["food"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cake.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "can",
    name: "Can",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "car",
    name: "Car",
    description: "vehicle, drive, wheels, transport, road",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/car.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "carrots",
    name: "Carrots",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cash",
    name: "Cash",
    description: "money, bills, currency, wealth, pay",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cash.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "castle",
    name: "Castle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat",
    name: "Cat",
    description: "animal, pet, feline, whiskers, mammal",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cat.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cat-on-lap",
    name: "Cat on lap",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat-on-mat",
    name: "Cat on Mat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cat-sleeping",
    name: "Cat sleeping",
    description: "cat, sleep, rest, pet, cozy",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cat-sleeping.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cat-with-carrots-cake-and-chocolate-chip-cookies",
    name: "Cat with Carrots, Cake, and Chocolate Chip Cookies",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cats-two",
    name: "Cats, two",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "caught",
    name: "Caught",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ceiling",
    name: "Ceiling",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chain",
    name: "Chain",
    description: "links, metal, connected, lock, strong",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/chain.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "chair",
    name: "Chair",
    description: "seat, furniture, sit, wood, rest",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/chair.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "chat",
    name: "Chat",
    description: "talk, conversation, message, speech, connect",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/chat.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "chick",
    name: "Chick",
    description: "bird, baby, yellow, hatch, cute",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/chick.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "chicken-pen",
    name: "Chicken Pen",
    description: "farm, chicken, fence, coop, animal",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/chicken-pen.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "child",
    name: "Child",
    description: "kid, youth, person, young, student",
    tags: ["people"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/child.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "chin",
    name: "Chin",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chocolate-chip-cookies",
    name: "Chocolate Chip Cookies",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chop",
    name: "Chop",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "chug",
    name: "Chug",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle",
    name: "Circle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle-of-people-reaching-overhead",
    name: "Circle of people reaching overhead",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle-large-dashed",
    name: "Circle, large dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "circle-small-dashed",
    name: "Circle, small dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cityscape",
    name: "Cityscape",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "clipboard-with-pencil",
    name: "Clipboard with Pencil",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "clothes",
    name: "Clothes",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cloud",
    name: "Cloud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "coach",
    name: "Coach",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "coat",
    name: "Coat",
    description: "clothing, warm, outerwear, winter, jacket",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/coat.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cod",
    name: "Cod",
    description: "fish, ocean, food, swim, aquatic",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cod.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "compare-4-similar-shapes",
    name: "Compare (4 similar shapes)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "compassion",
    name: "Compassion",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "contrast-4-different-shapes",
    name: "Contrast (4 different shapes)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cooking-kitchen",
    name: "Cooking/Kitchen",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cot",
    name: "Cot",
    description: "bed, sleep, portable, rest, camp",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cot.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cow",
    name: "Cow",
    description: "animal, farm, mammal, milk, spotted",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cow.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cube",
    name: "Cube",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cuff",
    name: "Cuff",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cup",
    name: "Cup",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cupcake",
    name: "Cupcake",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "cut",
    name: "Cut",
    description: "scissors, snip, slice, tool, craft",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cut.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cute",
    name: "Cute",
    description: "adorable, sweet, charming, soft, lovable",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/cute.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "cylinder",
    name: "Cylinder",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "den",
    name: "Den",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "detective",
    name: "Detective",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dig",
    name: "Dig",
    description: "shovel, dirt, hole, garden, excavate",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/dig.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "digging",
    name: "Digging",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dip",
    name: "Dip",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dog",
    name: "Dog",
    description: "animal, pet, puppy, loyal, mammal",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/dog.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "dog-puppy",
    name: "Dog, puppy",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "dog-spotted",
    name: "Dog, spotted",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "doll-falling",
    name: "Doll falling",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "donut",
    name: "Donut",
    description: "sweet, pastry, frosting, food, circular",
    tags: ["food"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/donut.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "drill",
    name: "Drill",
    description: "tool, hole, power, build, hardware",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/drill.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "drum",
    name: "Drum",
    description: "music, percussion, beat, rhythm, instrument",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/drum.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "duck",
    name: "Duck",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "duck-on-truck",
    name: "Duck on Truck",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "duck-toy",
    name: "Duck Toy",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ear",
    name: "Ear",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "earring",
    name: "Earring",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "egg",
    name: "Egg",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "eight",
    name: "Eight",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "elephant",
    name: "Elephant",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "empathy",
    name: "Empathy",
    description: "care, feelings, kindness, connect, heart",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/empathy.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "eye",
    name: "Eye",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "eyeball",
    name: "Eyeball",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "face-singing",
    name: "Face singing",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fan",
    name: "Fan",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fang",
    name: "Fang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feels-like-hearts",
    name: "Feels like (Hearts)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feet",
    name: "Feet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fern",
    name: "Fern",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "feud",
    name: "Feud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "field",
    name: "Field",
    description: "grass, outdoor, nature, open, landscape",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/field.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "figs",
    name: "Figs",
    description: "fruit, food, sweet, tree, purple",
    tags: ["food"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/figs.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "figures-in-a-circle-reaching-overhead",
    name: "Figures in a circle reaching overhead",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fin",
    name: "Fin",
    description: "fish, swim, ocean, aquatic, water",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/fin.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "fire",
    name: "Fire",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fish",
    name: "Fish",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fix",
    name: "Fix",
    description: "repair, tool, wrench, mend, broken",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/fix.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "flamingo",
    name: "Flamingo",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "flower",
    name: "Flower",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "flute",
    name: "Flute",
    description: "music, instrument, wind, melody, pipe",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/flute.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "fly",
    name: "Fly",
    description: "insect, wings, buzz, small, air",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/fly.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "fog",
    name: "Fog",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fold",
    name: "Fold",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fork",
    name: "Fork",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fox",
    name: "Fox",
    description: "animal, orange, mammal, wild, clever",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/fox.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "fox-on-box",
    name: "Fox on Box",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "frog-on-log",
    name: "Frog on Log",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "frown",
    name: "Frown",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "fruit",
    name: "Fruit",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "frying-pan",
    name: "Frying pan",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "full",
    name: "Full",
    description: "complete, filled, whole, maximum, plenty",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/full.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "fuzz",
    name: "Fuzz",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "glasses",
    name: "Glasses",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "glue",
    name: "Glue",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "goat-in-boat",
    name: "Goat in Boat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "gong",
    name: "Gong",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "goose-on-moose",
    name: "Goose on Moose",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "grass",
    name: "Grass",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hand-touch",
    name: "Hand (Touch)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hang",
    name: "Hang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hash",
    name: "Hash",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hat",
    name: "Hat",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hat-on-bat",
    name: "Hat on Bat",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hay",
    name: "Hay",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "head-with-question-mark-in-it",
    name: "Head with Question Mark in it",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "heart",
    name: "Heart",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hearts-dashed",
    name: "Hearts, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hen",
    name: "Hen",
    description: "chicken, farm, bird, egg, animal",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/hen.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "hiss",
    name: "Hiss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hive",
    name: "Hive",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hockey",
    name: "Hockey",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hoe",
    name: "Hoe",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "honk",
    name: "Honk",
    description: "horn, sound, loud, car, noise",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/honk.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "hops",
    name: "Hops",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "horse",
    name: "Horse",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "host",
    name: "Host",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "house-with-plant-sun-clouds",
    name: "House with plant, sun, clouds",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "huge",
    name: "Huge",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "hush",
    name: "Hush",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ice-cube",
    name: "Ice Cube",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "idea",
    name: "Idea",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "iguana",
    name: "Iguana",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "integrity",
    name: "Integrity",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "itch",
    name: "Itch",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jam",
    name: "Jam",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jazz",
    name: "Jazz",
    description: "music, improvisation, swing, notes, band",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/jazz.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "jellyfish",
    name: "Jellyfish",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "jug",
    name: "Jug",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "junk",
    name: "Junk",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "key",
    name: "Key",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "king",
    name: "King",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "kiss",
    name: "Kiss",
    description: "love, lips, affection, romance, soft",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/kiss.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "kite",
    name: "Kite",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "knee",
    name: "Knee",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ladder",
    name: "Ladder",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lake",
    name: "Lake",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "launch",
    name: "Launch",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "leaf",
    name: "Leaf",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lemur",
    name: "Lemur",
    description: "animal, primate, ringtail, wild, mammal",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/lemur.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "less",
    name: "Less",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lid",
    name: "Lid",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "light",
    name: "Light",
    description: "lamp, bright, glow, illuminate, bulb",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/light.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "lion",
    name: "Lion",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lips",
    name: "Lips",
    description: "mouth, kiss, smile, face, pink",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/lips.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "lipstick",
    name: "Lipstick",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "little-small",
    name: "Little/Small",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "llama",
    name: "Llama",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "log",
    name: "Log",
    description: "wood, tree, forest, trunk, nature",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/log.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "long",
    name: "Long",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "looking-through-binoculars",
    name: "Looking through Binoculars",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "looping-arrows-repeat",
    name: "Looping arrows (\"Repeat\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "lung",
    name: "Lung",
    description: "body, breath, organ, health, anatomy",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/lung.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "magnifying-glass-on-document-give-evidence",
    name: "Magnifying glass on document (\"Give evidence\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mail",
    name: "Mail",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "map",
    name: "Map",
    description: "travel, location, geography, route, explore",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/map.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "mat",
    name: "Mat",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "medium",
    name: "Medium",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mesh",
    name: "Mesh",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mill",
    name: "Mill",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mincing-chopping-board",
    name: "Mincing(chopping board)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mind",
    name: "Mind",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mink",
    name: "Mink",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "monkey-with-sock-puppets",
    name: "Monkey, with sock puppets",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "moons-dashed",
    name: "Moons, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mop",
    name: "Mop",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "moss",
    name: "Moss",
    description: "green, plant, nature, forest, soft",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/moss.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "motorcycle",
    name: "Motorcycle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mountain",
    name: "Mountain",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mouse-with-muffins-and-mushrooms",
    name: "Mouse, with Muffins and Mushrooms",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mud",
    name: "Mud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "muffins-and-mushrooms",
    name: "Muffins and Mushrooms",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mule",
    name: "Mule",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "music",
    name: "Music",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "mute",
    name: "Mute",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "nail",
    name: "Nail",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "nap",
    name: "Nap",
    description: "sleep, rest, sofa, tired, quiet",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/nap.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "nest",
    name: "Nest",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "newspaper-rolled",
    name: "Newspaper (rolled)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "newt",
    name: "Newt",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "night",
    name: "Night",
    description: "moon, stars, dark, evening, sky",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/night.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "nine",
    name: "Nine",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "nose-smell",
    name: "Nose (smell)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "octagon",
    name: "Octagon",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "octopus",
    name: "Octopus",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "oval",
    name: "Oval",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "oval-open",
    name: "Oval, Open",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl",
    name: "Owl",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl-with-balloon",
    name: "Owl, with Balloon",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl-with-sock",
    name: "Owl, with Sock",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "owl-with-sock-puppets",
    name: "Owl, with sock puppets",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paint",
    name: "Paint",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pang",
    name: "Pang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paper",
    name: "Paper",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paper-with-pencil-think-write-or-sketch",
    name: "Paper, with pencil (\"Think, write, or sketch\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "path",
    name: "Path",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "paw",
    name: "Paw",
    description: "animal, footprint, pet, print, claw",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/paw.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "pear",
    name: "Pear",
    description: "fruit, food, yellow, sweet, fresh",
    tags: ["food"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/pear.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "pencil",
    name: "Pencil",
    description: "write, draw, school, graphite, tool",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/pencil.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "penny",
    name: "Penny",
    description: "coin, money, copper, cent, currency",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/penny.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "pentagon-dashed",
    name: "Pentagon, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person",
    name: "Person",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-athlete",
    name: "Person, Athlete",
    description: "sport, person, fitness, run, active",
    tags: ["people"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/person-athlete.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "person-balancing-a-box",
    name: "Person, balancing a box",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-balancing-shapes-compare",
    name: "Person balancing shapes",
    description: "compare, balance, shapes, person, equal",
    subtitle: "(\"Compare\")",
    tags: ["people"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/person-balancing-shapes-compare.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "person-hammering-a-nail",
    name: "Person, hammering a nail",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-on-chair-looking-at-cactus-sun-clouds-birds",
    name: "Person, on chair looking at cactus, sun, clouds, birds",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-overboard-boat",
    name: "Person, Overboard (boat)",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-running",
    name: "Person, Running",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-speaking",
    name: "Person, speaking",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-stumbling",
    name: "Person, Stumbling",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-walking",
    name: "Person, walking",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-with-audio-player",
    name: "Person, with audio player",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-with-directional-arrows",
    name: "Person, with directional arrows",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-with-magnifying-glass",
    name: "Person, with magnifying glass",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-with-question-mark",
    name: "Person, with Question Mark",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "person-with-talk-bubble",
    name: "Person, with talk bubble",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pet",
    name: "Pet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "phone",
    name: "Phone",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pie",
    name: "Pie",
    description: "dessert, food, sweet, pastry, baked",
    tags: ["food"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/pie.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "piggy-bank",
    name: "Piggy Bank",
    description: "money, savings, pig, coin, bank",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/piggy-bank.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "pin",
    name: "Pin",
    description: "point, stick, marker, metal, attach",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/pin.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "plane",
    name: "Plane",
    description: "airplane, fly, travel, sky, transport",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/plane.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "plate-of-food",
    name: "Plate of Food",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "plates-of-food-and-teacup",
    name: "Plates of Food and Teacup",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "play-box",
    name: "Play/Box",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "play-dough",
    name: "Play Dough",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "play-with-blocks",
    name: "Play with Blocks",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pop",
    name: "Pop",
    description: "burst, balloon, sound, sudden, surprise",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/pop.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "pot",
    name: "Pot",
    description: "cook, kitchen, pot, food, stove",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/pot.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "potato-chips",
    name: "Potato chips",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puff",
    name: "Puff",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "pug",
    name: "Pug",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puppets",
    name: "Puppets",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "purse",
    name: "Purse",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "puzzle-piece-with-question-mark-challenge",
    name: "Puzzle piece with question mark",
    description: "puzzle, challenge, question, pieces, solve",
    subtitle: "(\"Challenge\")",
    tags: ["food"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/puzzle-piece-with-question-mark-challenge.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "puzzle-pieces",
    name: "Puzzle pieces",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "question-mark",
    name: "Question Mark",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "question-checkmark-speech-bubbles-clarify",
    name: "Question/checkmark speech bubbles (\"Clarify\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "racoon",
    name: "Racoon",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rain",
    name: "Rain",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rainbow",
    name: "Rainbow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rake",
    name: "Rake",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ram",
    name: "Ram",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rat",
    name: "Rat",
    description: "animal, rodent, mammal, whiskers, gray",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/rat.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "reading-a-book",
    name: "Reading a book",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rectangle",
    name: "Rectangle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "respect",
    name: "Respect",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ring",
    name: "Ring",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "road",
    name: "Road",
    description: "street, path, travel, asphalt, drive",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/road.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "road-block",
    name: "Road block",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "rod",
    name: "Rod",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "safe",
    name: "Safe",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sand",
    name: "Sand",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sand-castle",
    name: "Sand Castle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sang",
    name: "Sang",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sank",
    name: "Sank",
    description: "ship, sink, ocean, waves, underwater",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/sank.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "satellite-dish",
    name: "Satellite dish",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "scale-check-x",
    name: "Scale (check, X)",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "seal",
    name: "Seal",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sell",
    name: "Sell",
    description: "shop, money, trade, bag, exchange",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/sell.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "shed",
    name: "Shed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sheep",
    name: "Sheep",
    description: "animal, wool, farm, mammal, fluffy",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/sheep.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "shell",
    name: "Shell",
    description: "ocean, beach, seashell, nature, spiral",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/shell.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "shin",
    name: "Shin",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "ship",
    name: "Ship",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shirt",
    name: "Shirt",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shop",
    name: "Shop",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "shut",
    name: "Shut",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sing",
    name: "Sing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sink",
    name: "Sink",
    description: "faucet, water, kitchen, wash, plumbing",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/sink.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "sip",
    name: "Sip",
    description: "drink, straw, cup, beverage, taste",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/sip.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "skunk",
    name: "Skunk",
    description: "animal, black, white, stripe, mammal",
    tags: ["animal"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/skunk.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "small-steps",
    name: "Small steps",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "smile",
    name: "Smile",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "smiley-face-with-open-book",
    name: "Smiley Face with open Book",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snacks-popcorn-pizza-pretzel",
    name: "Snacks (popcorn, pizza, pretzel)",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snail-on-whale",
    name: "Snail on Whale",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snake",
    name: "Snake",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snake-on-cake",
    name: "Snake on Cake",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snake-with-soup-strawberries-and-sandwich",
    name: "Snake with Soup, Strawberries, and Sandwich",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "snow",
    name: "Snow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "soap",
    name: "Soap",
    description: "clean, wash, bubbles, bath, foam",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/soap.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "sock",
    name: "Sock",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "soil",
    name: "Soil",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "song",
    name: "Song",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "soup",
    name: "Soup",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "spring",
    name: "Spring",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "square",
    name: "Square",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "squares-dashed",
    name: "Squares, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "star",
    name: "Star",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "starfish",
    name: "Starfish",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "stick",
    name: "Stick",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "store",
    name: "Store",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sun",
    name: "Sun",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sun-dashed",
    name: "Sun, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sunflower",
    name: "Sunflower",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sung",
    name: "Sung",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sunglasses",
    name: "Sunglasses",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "sunk",
    name: "Sunk",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "swing",
    name: "Swing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "swings",
    name: "Swings",
    description: "playground, play, outdoor, fun, park",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/swings.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "tag",
    name: "Tag",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "talk-about-the-question",
    name: "Talk about the question",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tank",
    name: "Tank",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tape-dispenser",
    name: "Tape dispenser",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tea-cup",
    name: "Tea cup",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "teacher-reading-to-students",
    name: "Teacher, reading to students",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tears-dashed",
    name: "Tears, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "teeth",
    name: "Teeth",
    description: "tooth, smile, dental, white, mouth",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/teeth.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "tern",
    name: "Tern",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "the-magic-bow",
    name: "The Magic Bow",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thought",
    name: "Thought",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "three",
    name: "Three",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "three-people",
    name: "Three people",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "throne",
    name: "Throne",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thud",
    name: "Thud",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thumb",
    name: "Thumb",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "thumbs-up-down-agree-or-disagree",
    name: "Thumbs up/down (\"Agree or disagree\")",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tiger",
    name: "Tiger",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tiny",
    name: "Tiny",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tire",
    name: "Tire",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tissue",
    name: "Tissue",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toll",
    name: "Toll",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tongs",
    name: "Tongs",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tooth",
    name: "Tooth",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toothbrush",
    name: "Toothbrush",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "top",
    name: "Top",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toss",
    name: "Toss",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "toy",
    name: "Toy",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tractor",
    name: "Tractor",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "train",
    name: "Train",
    description: "railway, transport, tracks, travel, engine",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/train.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "treasure-chest",
    name: "Treasure Chest",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tree",
    name: "Tree",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "tree-without-leaves",
    name: "Tree without leaves",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "trees",
    name: "Trees",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "triangle",
    name: "Triangle",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "triangles-dashed",
    name: "Triangles, dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "turtle",
    name: "Turtle",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "turtle-with-plates-of-food-and-teacup",
    name: "Turtle with Plates of Food and Teacup",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-13.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-figures-fishing",
    name: "Two figures, fishing",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-figures-happy",
    name: "Two figures, happy",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-figures-talking-explain",
    name: "Two figures, talking (\"Explain\")",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "two-figures-talking-business",
    name: "Two figures, talking business",
    tags: ["people"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "type",
    name: "Type",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "umbrella",
    name: "Umbrella",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "van",
    name: "Van",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-01.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "vet",
    name: "Vet",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-02.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "want-to-play",
    name: "Want to Play",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-03.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "warning-symbol",
    name: "Warning Symbol",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-04.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "water",
    name: "Water",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-05.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "watermelon",
    name: "Watermelon",
    tags: ["food"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-06.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "web",
    name: "Web",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-07.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wedding-rings",
    name: "Wedding rings",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-08.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "where",
    name: "Where",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-09.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wig",
    name: "Wig",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-10.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "win",
    name: "Win",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-11.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wing",
    name: "Wing",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-12.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "wink",
    name: "Wink",
    description: "eye, face, playful, emoji, expression",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/wink.png",
    sourceMime: "image/png",
    status: "done",
  },
  {
    id: "wolf",
    name: "Wolf",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-14.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "yell",
    name: "Yell",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-15.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zebra",
    name: "Zebra",
    tags: ["animal"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-16.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zero",
    name: "Zero",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-17.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zig-zag-large-dashed",
    name: "Zig zag, large dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-18.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zig-zag-small-dashed",
    name: "Zig zag, small dashed",
    tags: ["object"],
    illustrator: null,
    previewUrl: "assets/placeholders/placeholder-19.png",
    sourceMime: "image/png",
    status: "needed",
  },
  {
    id: "zip",
    name: "Zip",
    description: "zipper, close, clothing, fastener, pull",
    tags: ["object"],
    illustrator: "Kemal Sanli",
    previewUrl: "assets/illustrations/zip.png",
    sourceMime: "image/png",
    status: "done",
  }
];
